server:
  port: 8081
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sast_pancake
    driver-class-name: com.mysql.cj.jdbc.Driver

